PrintComment: ThisGoesHere overwrites AMP configs with reforge changes
CopyFile:
- From: config/overrides/FixItFelix.AutoMapPins.categories.vanilla.yaml
  To: config/FixItFelix.AutoMapPins.categories.vanilla.yaml
